#!/bin/bash
if [ -z "$PYFILE" ]; then
    echo "The PYFILE environment variable is not set."
    exit 1
fi

output_file="${PYFILE}c"
echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE" 2>/dev/null || python3 -m compileall "$PYFILE" 2>/dev/null

if [ -e "__pycache__" ]; then
    pyc_file="$(find __pycache__ -type f -name '*.pyc')"
    mv "$pyc_file" "$output_file"
    rm -rf "__pycache__"
else
    echo "Compilation failed."
    exit 1
fi

